server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: sams-enterprise-backend

  profiles:
    active: dev
    
  # Use H2 in-memory database for development
  datasource:
    url: jdbc:h2:mem:sams_enterprise
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  # Disable Redis for development
  cache:
    type: simple
    
  # Disable Kafka for development
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.ldap.LdapDataAutoConfiguration
      - org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration

  # Disable mail for development
  mail:
    host: localhost
    port: 25
    
# JWT Configuration
jwt:
  secret: sams-enterprise-dev-secret-key-2024
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

# Disable third-party integrations for development
integrations:
  slack:
    webhook-url: 
    bot-token: 
  teams:
    webhook-url: 
  twilio:
    account-sid: 
    auth-token: 
    from-number: 

# SAMS Enterprise Configuration
sams:
  enterprise:
    alert:
      max-correlation-window: 300000 # 5 minutes
      max-batch-size: 100
      processing-interval: 5000 # 5 seconds
    monitoring:
      agent-heartbeat-interval: 30000 # 30 seconds
      agent-timeout: 120000 # 2 minutes
      metrics-retention-days: 90
    security:
      max-login-attempts: 5
      lockout-duration: 900000 # 15 minutes
      session-timeout: 1800000 # 30 minutes
      mfa-enabled: false # Disabled for development
    performance:
      max-concurrent-connections: 1000
      rate-limit-requests-per-minute: 1000
      cache-ttl: 300000 # 5 minutes

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.sams.enterprise: DEBUG
    org.springframework.security: INFO
    org.springframework.kafka: WARN
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
